trigger:
  branches:
    include:
      - main
      - develop
      - feature/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  SONAR_PROJECT_KEY: 'bizca_bizca'
  SONAR_ORGANIZATION: 'bizca'
  DOTNET_VERSION: '8.0.x'

steps:
  - checkout: self

  - task: UseDotNet@2
    displayName: 'Install .NET SDK'
    inputs:
      packageType: 'sdk'
      version: '$(DOTNET_VERSION)'

  - task: SonarCloudPrepare@1
    displayName: 'Prepare SonarCloud analysis'
    inputs:
      SonarCloud: 'SonarCloud'  # doit être configuré dans Project Settings > Service connections
      organization: '$(SONAR_ORGANIZATION)'
      scannerMode: 'MSBuild'
      projectKey: '$(SONAR_PROJECT_KEY)'
      projectName: 'bizca'

  - script: |
      dotnet restore bizca.sln
      dotnet build bizca.sln --configuration $(buildConfiguration) --no-incremental --no-restore
    displayName: 'Build the solution with dotnet build'

  - script: |
      dotnet test bizca.sln --configuration $(buildConfiguration) --no-build --collect:"XPlat Code Coverage"
    displayName: 'Run tests'

  - task: SonarCloudAnalyze@1
    displayName: 'Run SonarCloud analysis'

  - task: SonarCloudPublish@1
    displayName: 'Publish SonarCloud results'
    inputs:
      pollingTimeoutSec: '300'
