<Project>

	<PropertyGroup>
		<Authors>Bizca</Authors>
		<Company>Bizca</Company>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<CodeAnalysisTreatWarningsAsErrors>true</CodeAnalysisTreatWarningsAsErrors>
		<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
		<AnalysisLevel>latest</AnalysisLevel>
		<AnalysisMode>All</AnalysisMode>
		<LangVersion>latest</LangVersion>
		<IsTestProject>$([System.String]::Copy('$(MSBuildProjectName)').Contains('Tests'))</IsTestProject>
		<RepositoryUrl>https://github.com/Letsafko/Bizca</RepositoryUrl>
		<NoWarn>S4035;CA2225;CA1812;S3459;CS0649;IDE0032</NoWarn>
	</PropertyGroup>

	<PropertyGroup Condition="'$(IsTestProject)' == 'false'">
		<IsPackable>true</IsPackable>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>

	<PropertyGroup Condition="'$(IsTestProject)' == 'true'">
		<IsPackable>false</IsPackable>
		<GenerateDocumentationFile>false</GenerateDocumentationFile>
	</PropertyGroup>

	<ItemGroup Condition="'$(MSBuildProjectExtension)' != '.dcproj'">
		<PackageReference Include="SonarAnalyzer.CSharp">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup Condition="'$(IsTestProject)' == 'false'">
		<PackageReference Include="System.Net.Http"/>
		<PackageReference Include="System.Text.RegularExpressions"/>
	</ItemGroup>

	<ItemGroup Condition="'$(IsTestProject)' == 'true'">
		<PackageReference Include="Microsoft.Extensions.TimeProvider.Testing"/>
		<PackageReference Include="Bogus"/>
		<PackageReference Include="AutoFixture"/>
		<PackageReference Include="RichardSzalay.MockHttp"/>
		<PackageReference Include="FluentAssertions"/>
		<PackageReference Include="Moq.Contrib.HttpClient"/>
		<PackageReference Include="coverlet.collector">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="FluentAssertions.Analyzers">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="xunit"/>
		<PackageReference Include="xunit.runner.visualstudio">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.NET.Test.Sdk"/>
	</ItemGroup>

</Project>