services:
  bizca.users.api:
    image: ${DOCKER_REGISTRY-}webapi
    container_name: bizca.users.api
    build:
      context: .
      dockerfile: microservices/user/Bizca.Users.Api/Dockerfile
    ports:
      - 5000:8080
      - 5001:8081

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      SA_PASSWORD: Password0@
      DB_USER: SA
      DB_NAME: bizca-user
    ports:
      - 1433:1433
    volumes:
      - mssql-data:/var/opt/mssql

  mssql-init:
    image: mcr.microsoft.com/mssql-tools:latest
    container_name: mssql-init
    depends_on:
      - mssql
    entrypoint: /bin/bash
    command: -c "sleep 15; /opt/mssql-tools/bin/sqlcmd -S mssql,1433 -U SA -P 'Password0@' -Q \"IF DB_ID(N'bizca-user') IS NULL CREATE DATABASE [bizca-user]\""
    restart: 'no'

  seq:
    image: datalust/seq:2024.3
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 8081:80

volumes:
  mssql-data:
  shared-seed:
    driver: local

