<Project Sdk="Aspire.AppHost.Sdk/13.1.1">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <UserSecretsId>f0b07601-8a43-4180-bd8d-6d25f5d17751</UserSecretsId>
    </PropertyGroup>

		<ItemGroup>
			<PackageReference Include="Aspire.Hosting.SqlServer" />
			<PackageReference Include="CommunityToolkit.Aspire.Hosting.SqlServer.Extensions" />
		</ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Bizca.Users.Api\Bizca.Users.Api.csproj" />
    </ItemGroup>

</Project>
