<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<RootNamespace>Bizca.Sdk.SharedKernel</RootNamespace>
		<AssemblyName>Bizca.Sdk.SharedKernel</AssemblyName>
		<PackageId>Bizca.Sdk.SharedKernel</PackageId>
		<Description>Bizca Sdk SharedKernel nuget</Description>
		<IsPackable>true</IsPackable>
	</PropertyGroup>
	<ItemGroup>
	  <Reference Include="Microsoft.Extensions.DependencyInjection.Abstractions">
	    <HintPath>C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\10.0.3\Microsoft.Extensions.DependencyInjection.Abstractions.dll</HintPath>
	  </Reference>
	</ItemGroup>
</Project>
